### ISSUE TITLE
Not working on live site!

### ISSUE THREAD

**Issue by HeadStudios** [stepanenko3/nova-settings#10]
Hi,

I've just noticed that while settings() function works fine on my staging it does not work on my live. I've reviewed to confirm everything is the same and I can't find any differences. When I do settings('env'); on live site it comes back with empty array [] but it does come back with the correct values on the staging site.

I know both staging and live are using the same database and I was wondering if you could suggest some troubleshooting steps to find out why this is happening. Thank you!

**Comment by stepanenko3** [comment]
Hi, @HeadStudios 

Perhaps you have created a resource with settings for "development" (Indicated in the "Env" field of the settings resource), but not created for "production", or is "production" empty?

**Comment by HeadStudios** [comment]
> You could just create a separate record of settings for production )) And edit production and development separately

Thank you! Yes I just realised that there is a text field to set which environment these settings should apply to. All fixed. Thank you for the quick response. Chrs.
